import Head from "next/head";
import Header from "../components/header";
import Redes from "../components/redes";
import Titulo from "../components/titulo";
import TituloSection from "../components/titulo-section";
import Skills from "../components/skills";

export default function Home() {
  return (
    <>
      <div className="App">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header>
          <div className="titles">
            <Titulo />
            <Titulo texto="Desarrollador Web" />
          </div>

          <Redes />
        </Header>

        <main>
          <section>
            <p>
              Hola! mi nombre es Nahuel, soy Desarrollador Web y aunque me
              enfoco principalmente en frontend, cuento con algo de experiencia
              en backend.
            </p>
          </section>
          <section>
            <TituloSection texto="Conocimientos" />
            <Skills />
          </section>
          <section>
            <TituloSection texto="Trabajos realizados" />
          </section>
        </main>

        <footer>
          <p>Página diseñada y programada por @nahuetomas</p>
        </footer>
      </div>

      <style jsx>{`
        section {
          max-width: 500px;
          margin: 80px auto;
        }

        section p {
          font-weight: bolder;
        }

        p {
          font-weight: lighter;
          max-width: 350px;
          text-align: center;
          font-size: 16px;
          margin: 10px auto;
        }

        footer {
          border-top: 1px solid #000;
          padding-top: 20px;
        }
      `}</style>
    </>
  );
}
