import Head from "next/head";
import Header from "../components/header";
import Redes from "../components/redes";
import Titulo from "../components/titulo";
import TituloSection from "../components/titulo-section";
import Skills from "../components/skills";

export default function Home() {
  return (
    <>
      <div className="App">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header>
          <div className="titles">
            <Titulo />
            <Titulo texto="Diseñador Web" />
          </div>

          <Redes />
        </Header>

        <main>
          <section>
            <p>
              Hola! mi nombre es Nahuel, soy Desarrollador Web y aunque me
              enfoco principalmente en frontend, cuento con algo de experiencia
              en backend.
            </p>
          </section>
          <section>
            <TituloSection texto="Conocimientos" />
            <Skills />
          </section>
          <section></section>
        </main>

        <footer></footer>
      </div>

      <style jsx>{`
        section {
          max-width: 500px;
          margin: 80px auto;
        }

        section p {
          max-width: 350px;
          font-weight: bolder;
          text-align: center;
          font-size: 16px;
          margin: auto;
        }
      `}</style>
    </>
  );
}
